# Generated by Django 4.2.9 on 2024-02-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_dependencia_user_nombre_alter_user_antiguedad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='antiguedad',
            new_name='antiquity',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dependencia',
            new_name='dependency',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='puesto',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='edad',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rango',
        ),
        migrations.AddField(
            model_name='user',
            name='workstation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
