# Generated by Django 4.2.9 on 2024-02-20 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etapa', '0002_rename_nombre_estapa_etapa_nombre_etapa'),
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id_voto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_voto', models.DateTimeField(auto_now=True)),
                ('estatus_revocacion', models.BooleanField(blank=True, default=False, null=True)),
                ('id_emp_candidato_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos_como_candidato', to=settings.AUTH_USER_MODEL)),
                ('id_emp_votante_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos_como_votante', to=settings.AUTH_USER_MODEL)),
                ('id_etapa_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapa.etapa')),
                ('id_rango_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rango.rango')),
            ],
        ),
    ]
