# Generated by Django 4.2.9 on 2024-02-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0002_rename_nombre_estapa_etapa_nombre_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
