# Generated by Django 4.2.9 on 2024-02-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0003_etapa_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='image',
        ),
    ]
